name: my first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4  
        - name: Wekcome message 
          run: echo "My first GitHum action job"

        - name: List files 
          run: ls

        - name: Read file 
          run: cat README.md
