name: generate ascii dragon with script

on: push

jobs:
    ascii-dragon-script_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repo
          uses: actions/checkout@v4  

        - name: List Repo Files
          run: ls -ltra    

        - name: Exicute shell script
          run:  |
                chmod +x ascii-script.sh
                ./ascii-script.sh

                
# chmod +x ascii-script.sh     (for giving permission )               